# Generated by Django 3.1.5 on 2021-01-31 06:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
                ('imagen_categoria', models.ImageField(help_text='Imagen 573x380, tamaño máximo de 350KB', upload_to='media', verbose_name='Imagen de Categoria')),
            ],
            options={
                'verbose_name': 'Categoria para Artículo',
                'verbose_name_plural': 'Categorias para Artículos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de Categoria')),
            ],
            options={
                'verbose_name': 'Categoria para Producto',
                'verbose_name_plural': 'Categorias para Productos',
            },
        ),
        migrations.CreateModel(
            name='ClienteDestacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=40, verbose_name='Nombre de la empresa cliente')),
                ('nombre_cliente', models.CharField(blank=True, max_length=40, verbose_name='Nombre de la persona contacto')),
                ('imagen_cliente', models.ImageField(help_text='Imagen 160x150, tamaño máximo de 350KB', upload_to='media', verbose_name='Imagen del cliente')),
            ],
            options={
                'verbose_name': 'Cliente Destacado',
                'verbose_name_plural': 'Clientes Destacados',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_derecha', models.TextField(help_text='Texto que aparecerá en la sección Contáctanos.', max_length=300, verbose_name='Texto Columna Derecha')),
                ('descripcion_pie', models.TextField(help_text='Texto que aparecerá en el pie de página del sitio web.', max_length=300, verbose_name='Texto Pie de Página')),
                ('ubicacion', models.CharField(blank=True, help_text='Escribe la ciudad y el país donde se ubica tu empresa.', max_length=100, verbose_name='Ubicación')),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('sitio_web', models.URLField(blank=True, help_text='Escribe la URL de un sitio web.')),
                ('facebook', models.URLField(blank=True, help_text='Escribe la URL de tu página de Facebook.')),
                ('instagram', models.URLField(blank=True, help_text='Escribe la URL de tu página de Instagram.')),
            ],
            options={
                'verbose_name': 'Sección Contáctanos',
                'verbose_name_plural': 'Sección Contáctanos',
            },
        ),
        migrations.CreateModel(
            name='InfoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nosotros', models.CharField(help_text='Título que aparecerá en la sección Nosotros.', max_length=60, verbose_name='Título de Sección')),
                ('introduccion', models.TextField(help_text='Escribe una breve introducción sobre tu empresa. Este será el primer párrafo de la sección.', verbose_name='Breve Introducción')),
                ('parrafo_dos', models.TextField(blank=True, help_text='Describe tu empresa más a detalle. Este será el texto principal de la sección.', verbose_name='Párrafo Principal')),
                ('imagen_nosotros', models.ImageField(help_text='Imagen 530x350, tamaño máximo de 1MB.', upload_to='media', verbose_name='Imagen de Sección')),
                ('logo_empresa', models.ImageField(blank=True, help_text='Imagen 250x60, tamaño máximo de 350KB.', upload_to='media', verbose_name='Logo de la empresa')),
            ],
            options={
                'verbose_name': 'Sección Nosotros',
                'verbose_name_plural': 'Sección Nosotros',
            },
        ),
        migrations.CreateModel(
            name='PortadaPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_banner', models.ImageField(help_text='Imagen 1920x470, tamaño máximo de 1MB.', upload_to='media', verbose_name='Imagen de Portada')),
                ('titulo', models.CharField(blank=True, help_text='Título que aparecerá en la Portada.', max_length=60, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, help_text='Subtítulo que aparecerá en la Portada.', max_length=60, verbose_name='Subtítulo')),
                ('parrafo', models.TextField(blank=True, help_text='Párrafo corto que aparecerá en la portada. Usa ENTER para saltos de línea.', max_length=300, verbose_name='Párrafo')),
                ('color_texto', models.CharField(choices=[('text', 'Blanco'), ('dark', 'Negro')], default='dark', help_text='Seleccione un color.', max_length=4, verbose_name='Color del Texto')),
                ('primera_portada', models.CharField(choices=[('active', 'Si'), ('inactive', 'No')], default='inactive', help_text='¿Usar como Primera Portada?', max_length=8, verbose_name='Primera Portada')),
            ],
            options={
                'verbose_name': 'Portada del Sitio Web',
                'verbose_name_plural': 'Portadas del Sitio Web',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(help_text='Este campo crea la URL del perfil de este producto. Cambia si el nombre del producto cambia.', max_length=100)),
                ('imagen', models.ImageField(help_text='Imagen 573x380, tamaño máximo de 350KB.', upload_to='media', verbose_name='Imagen del producto')),
                ('descripcion', models.TextField(help_text='Escribe una breve descripción del producto.', verbose_name='Descripción')),
                ('categoria', models.ForeignKey(help_text='Selecciona una categoria para el producto.', on_delete=django.db.models.deletion.CASCADE, to='datospaginas.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=50, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(help_text='Escribe una breve descripción del servicio.', max_length=300, verbose_name='Descripción Breve')),
                ('descripcion_detalle', models.TextField(blank=True, help_text='Describe detalladamente el servicio.', max_length=800, verbose_name='Descripción Detallada')),
                ('imagen_servicio', models.ImageField(help_text='Imagen 573x380, tamaño máximo de 350KB.', upload_to='media', verbose_name='Imagen del Servicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Corto mensaje que aparecerá junto al Producto Destacado.', max_length=40, verbose_name='Mensaje')),
                ('producto', models.ForeignKey(blank=True, help_text='Seleccione un Producto.', null=True, on_delete=django.db.models.deletion.CASCADE, to='datospaginas.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto Destacado',
                'verbose_name_plural': 'Productos Destacados',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título')),
                ('introduccion', models.TextField(help_text='Este será el primer párrafo de tu artículo.', verbose_name='Breve Introducción')),
                ('contenido', models.TextField(help_text='Escribe el texto principal de tu artículo.', verbose_name='Contenido del Artículo')),
                ('imagen_post', models.ImageField(help_text='Imagen 940x620, tamaño máximo de 1MB.', upload_to='media', verbose_name='Imagen del Artículo')),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('estado_publicacion', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], help_text='Esta opción te permite guardar los datos en borrador sin publicarlos en el sitio web.', max_length=10, verbose_name='Estado del artículo')),
                ('categoria', models.ForeignKey(help_text='Selecciona una categoria para el artículo.', on_delete=django.db.models.deletion.CASCADE, to='datospaginas.categoriablog')),
            ],
            options={
                'verbose_name': 'Artículo del Blog',
                'verbose_name_plural': 'Artículos del Blog',
            },
        ),
    ]
