# Generated by Django 3.1.5 on 2021-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datospaginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_nosotros', models.CharField(help_text='Título que aparecerá en la sección Nosotros.', max_length=60, verbose_name='Título de Sección')),
                ('introduccion', models.TextField(help_text='Escribe una breve introducción sobre tu empresa. Este será el primer párrafo de la sección.', verbose_name='Breve Introducción')),
                ('parrafo_dos', models.TextField(blank=True, help_text='Describe tu empresa más a detalle. Este será el texto principal de la sección.', verbose_name='Párrafo Principal')),
                ('imagen_nosotros', models.ImageField(help_text='Imagen 530x350, tamaño máximo de 1MB.', upload_to='media', verbose_name='Imagen de Sección')),
            ],
            options={
                'verbose_name': 'Sección Nosotros',
                'verbose_name_plural': 'Sección Nosotros',
            },
        ),
        migrations.DeleteModel(
            name='InfoEmpresa',
        ),
        migrations.AddField(
            model_name='contacto',
            name='logo_empresa',
            field=models.ImageField(blank=True, help_text='Imagen 250x60, tamaño máximo de 350KB.', upload_to='media', verbose_name='Logo de la empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sitio_web',
            field=models.CharField(blank=True, help_text='Escribe la URL de un sitio web.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ubicacion',
            field=models.CharField(help_text='Escribe la ciudad y el país donde se ubica tu empresa.', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Escribe una descripción del producto.', verbose_name='Descripción'),
        ),
    ]
