# Generated by Django 3.1.5 on 2021-02-04 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datospaginas', '0002_auto_20210204_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=ckeditor.fields.RichTextField(help_text='Escribe el texto principal de tu artículo.', verbose_name='Contenido del Artículo'),
        ),
    ]
